Refactoring of parent POM file
aservo/parent-pom pull request #1
Opened 2022-03-11 06:11 UTC by brettaufheber

Hello @pathob ,
please let me know what you think about this changes.

2022-03-12 06:05 UTC, pathob requested changes
Siehe Teams

2022-03-12 06:05 UTC, pathob commented on pom.xml
> +        <exec.plugin.version>3.0.0</exec.plugin.version>
Sortierung

2022-03-12 06:05 UTC, pathob commented on pom.xml
> -
Wieso macht es im DependencyManagement Block Probleme?

2022-03-12 06:05 UTC, pathob commented on pom.xml
> +            <id>testing-it</id>
Zusammen mit: [Add profile for testing tools and allow integration tests](https://github.com/aservo/parent-pom/pull/1/commits/27c59825e4f29858448d481e8b68ac19074d2817)[](https://github.com/brettaufheber)

2022-03-14 06:28 UTC, brettaufheber commented on pom.xml
> +<project
Ich würde gerne, das Auto-Formatierungs-Tool meiner IDE einsetzen. Das habe ich auch für die nachfolgenden Commits gebraucht. In den "confapi"-Projekten ist eine solche Formatierung bereits erfolgt.

2022-03-14 06:37 UTC, brettaufheber commented on pom.xml
> -
Abhängigkeiten in der Parent-POM zu verankern finde ich nicht gut. Das könnte potentiell zu Versionskonflikten führen. Künftig wird nicht jedes Projekt ein "confapi"-Projekt darstellen, sodass man solche Konfiguration eventuell an eine andere Stelle auslagern sollte. Ich bin prinzipiell dafür, so wenig wie möglich Abhängigkeiten in einem Projekt zu haben, ganz besonders dann, wenn diese eventuell gar keine Anwendung finden.

2022-03-14 06:44 UTC, brettaufheber commented on pom.xml
> +            <id>pathob</id>
Anders als bei manch anderen Stellen in der POM, wird das ID Feld hier nicht nur für die interne Verarbeitung genutzt.
Ich zitiere aus https://maven.apache.org/pom.html#Developers
`id, name, email: These correspond to the developer's ID (presumably some unique ID across an organization), the developer's name and email address.`
**Habe die Änderung entfernt.**

2022-03-14 06:48 UTC, brettaufheber commented on pom.xml
> +        <connection>scm:git:https://github.com/aservo/parent-pom.git</connection>
Im Gegensatz zu "developerConnection" soll "connection" auch funktionieren, wenn keine Secrets wie Credentials oder User-Token bekannt sind.

2022-03-14 06:56 UTC, brettaufheber commented on pom.xml
> +    <version>1.0.0</version>
Habe ich angepasst.

2022-03-14 06:57 UTC, brettaufheber commented on pom.xml
> +<project
Ich habe nun die selbe Formatierung wie bei den "confapi"-Projekten gewählt.

2022-03-14 07:00 UTC, brettaufheber commented on pom.xml
> -        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
Gegenfrage: Warum ist die "settings.xml" im Verzeichnis ".github/workflows" eingecheckt?
Sicherlich aus dem Grund, die Projektspezifischen Konfigurationen von dem eigentlichen Projekt-Code zu trennen.

2022-03-14 07:01 UTC, brettaufheber commented on pom.xml
> -        <allow.google.tracking>false</allow.google.tracking>
Habe ich angepasst.

2022-03-14 08:44 UTC, brettaufheber commented on pom.xml
> -        <allow.google.tracking>false</allow.google.tracking>
Wozu eigentlich?

2022-03-14 08:46 UTC, brettaufheber commented on pom.xml
> +
Habe ich angepasst.

2022-03-14 08:46 UTC, brettaufheber commented on pom.xml
> +            <id>testing-it</id>
Habe ich angepasst.

2022-03-14 08:49 UTC, brettaufheber commented on pom.xml
> +        <sonar.plugin.version>3.9.1.2184</sonar.plugin.version>
Das ist nun wirklich eine Sache, die in einem Kommentar erwähnt werden sollte.
Habe ich angepasst.

2022-03-14 09:06 UTC, brettaufheber commented on pom.xml
> +        <gpg.plugin.version>3.0.1</gpg.plugin.version>
Habe ich angepasst.

2022-03-14 09:06 UTC, brettaufheber commented on pom.xml
> +        <nexus-staging.plugin.version>1.6.8</nexus-staging.plugin.version>
Habe ich angepasst.

2022-03-14 09:06 UTC, brettaufheber commented on pom.xml
> +        <jacoco.plugin.version>0.8.7</jacoco.plugin.version>
Habe ich angepasst.

2022-03-14 09:07 UTC, brettaufheber commented on pom.xml
> +        <swagger.plugin.version>2.1.1</swagger.plugin.version>
Habe ich angepasst.

2022-03-14 09:07 UTC, brettaufheber commented on pom.xml
> +        <exec.plugin.version>3.0.0</exec.plugin.version>
Habe ich angepasst.

2022-03-14 13:19 UTC, pathob requested changes
Eine generelle Anmerkung zu den sehr klein geschnittenen Commits. In "Refactor deploying" wird das Distribution Management durch ein property-basiertes in einem Profile ersetzt. Aber erst mit dem letzten Commit "Update workflow scripts" werden die Änderungen angewendet und die neuen Properties eingeführt. Dasselbe gilt für die Aktivierung der notwendigen Profile in der Pipeline. Damit sind die Commits nicht disjunkt und wenn ich die Änderungen einzeln cherry-picken würde, würde die Pipeline mit einem der mittleren Commits fehlschlagen und erst mit dem letzten Commit wieder funktionieren.

Trotzdem bin ich bereit, die Änderungen, die funktional gut sind, zu mergen wenn folgende Dinge umgesetzt werden:

* DROP: Reformat POM file
* SQUASH (das sind alles "small adjustments"):
  * Do some small adjustments
  * Remove project specific properties
  * Unify default plugin properties

Ich persönlich würde noch andere Commits zusammenpacken, aber das hier sind die für mich offensichtlichen.

2022-03-17 12:27 UTC, brettaufheber commented
Hallo @pathob,
deinem Wunsch "Remove project specific properties" mit einem Squash in "Do some small adjustments" zu überführen kann ich nicht entsprechen, weil das Entfernen der Dependencies aus der Parent-POM potentiell einen Build-Breaker für die abhängigen Projekte darstellt.

2022-03-17 12:35 UTC, pathob commented
@brettaufheber Der gesamte PR ist ein Buildbreaker, deshalb wird mit dem ersten Commit eine neue Major Version gestartet.

2022-03-30 12:19 UTC, merged